baseURL = "https://fabienhure.com/"
languageCode = "en-gb"
title = "Fabien Huré"
theme = "PaperMod"

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
    author = "Fabien Huré"
    description = "Notes on quantitative finance, analytics platforms, and engineering trade-offs."
    defaultTheme = "auto"
    ShowReadingTime = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowPostNavLinks = true

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/fabien-hur%C3%A9/"
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Genst"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:contact@fabienhure.com"
    mainSections = ["blog"]

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 30
